Дополнительно. Исправлены недочеты, добавлены тесты, добавлено логирование
gpb-it-factory/danyukovas-telegram-bot pull request #16
Opened 2024-06-26 22:12 UTC by SiuSpacecowboy

2024-06-29 11:30 UTC, vaganov-vadim requested changes
Привет! Круто, что добавил логи. По сути есть общая проблема в большинстве сообщений - нет контекста, неясно, как нам это поможет при поддержке приложения, если мы даже не знаем, какой пользователь это отправил. В общем, давай попробуем добавить служебной информации.

2024-06-29 11:30 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/handlers/NotTextCommand.java
> +        log.info("Формирование ответа сообщения при запросе не в виде текста.");
По текущему сообщению очень сложно понять, к чему относится сообщение. Например, какой клиент это отсылает.

2024-06-29 11:30 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/handlers/PingCommand.java
> +        log.info("Исполнение команды /ping.");
Аналогично, по сути сама по себе такая информация без контекста исполнения не очень полезна.

2024-06-29 11:30 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/services/BotService.java
> +                log.error("Критическая ошибка при отправке сообщения в тг.");
А где сама ошибка? По сути нет смысла в таком логе, если дальше ошибку пробрасываешь и она где-то ещё обработается.

2024-06-29 11:30 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/services/BotService.java
>                  throw new RuntimeException(e);
Думаю, можно более специализированную ошибку здесь сделать, а не просто Runtime.

2024-07-01 16:27 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/handlers/PingCommand.java
> +        log.info("Исполнение команды /ping.");
Готово

2024-07-01 16:27 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/handlers/NotTextCommand.java
> +        log.info("Формирование ответа сообщения при запросе не в виде текста.");
Исправлено

2024-07-01 16:39 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/services/BotService.java
> +                log.error("Критическая ошибка при отправке сообщения в тг.");
сделано

2024-07-01 16:39 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/services/BotService.java
>                  throw new RuntimeException(e);
Сделал, но не уверен, что оптимально

2024-07-01 17:43 UTC, vaganov-vadim approved these changes
Аппрув

2024-07-01 21:18 UTC, merged