Feature/1
gpb-it-factory/danyukovas-telegram-bot pull request #2
Opened 2024-05-06 21:37 UTC by SiuSpacecowboy

2024-05-08 05:26 UTC, vaganov-vadim commented
Привет! Как минимум - поправь название MR под соглашение, указанное в репозитории практики. С коммитами тоже - сейчас исправлять не надо, он на будущее - давай по соглашению.

2024-05-08 11:07 UTC, konstantin-kozlovskiy commented on README.md
> +обрабатывать транзакции(выступать в роли автоматизированной банковской системы).
не то чтобы я сильно докапывался, но 3 пункт странно рендерится в маркдауне ) 
![image](https://github.com/gpb-it-factory/danyukovas-telegram-bot/assets/168074443/02b2f10d-0589-4e47-9234-93976664ee53)
перенос строки выглядит лишним

2024-05-08 11:27 UTC, konstantin-kozlovskiy submitted a review, later dismissed

2024-05-08 13:35 UTC, SiuSpacecowboy commented on README.md
> +обрабатывать транзакции(выступать в роли автоматизированной банковской системы).
Я сейчас хочу исправить эту ошибку, получается я должен создать новый пулл реквест, а этот закрыть?

2024-05-13 16:12 UTC, vaganov-vadim commented on README.md
> +обрабатывать транзакции(выступать в роли автоматизированной банковской системы).
Решили вопрос. Работаем в рамках PR. Я добавлю это в репозиторий практики.

2024-05-14 05:36 UTC, vaganov-vadim commented
Привет! Как минимум - поправь название PR под соглашение, указанное в репозитории практики. С коммитами тоже - сейчас исправлять не надо, он на будущее - давай по соглашению.

2024-05-14 05:39 UTC, vaganov-vadim requested changes
В целом хорошо, но давай добавим информации в README и поправим название PR под соглашения, указанные в репозитории практики.

2024-05-14 05:39 UTC, vaganov-vadim commented on README.md
> +# Приложение разработанное в рамках [GPB IT Factory Backend 2024](https://gpb.fut.ru/itfactory/backend) будет содержать:
Предлагаю добавить здесь описание именно этого репозитория. Что в нём будет находиться? Зачем он нужен?

2024-05-14 05:39 UTC, vaganov-vadim commented on README.md
> +1. Frontend часть, которая будет реализована с помощью telegram-bot'а на java.
А зачем она нужна? =)

2024-05-17 09:09 UTC, SiuSpacecowboy reviewed
Исправление README файла

2024-05-20 05:31 UTC, vaganov-vadim commented
Тут указано про название PR (такие соглашения могут быть важны для различных автоматизаций) - https://github.com/gpb-it-factory/practice/blob/trunk/README.md
Поправь и вливаем.

2024-05-20 13:32 UTC, vaganov-vadim requested changes
Меняем название PR и вливаем =)

2024-05-21 05:44 UTC, vaganov-vadim approved these changes

2024-05-21 12:10 UTC, merged