Задание 6. Добавлена функциональность под запросы в middle-service
gpb-it-factory/danyukovas-telegram-bot pull request #9
Opened 2024-05-31 22:21 UTC by SiuSpacecowboy

2024-06-07 00:39 UTC, SiuSpacecowboy commented
- Хотелось бы узнать, насколько моя requestFactory это хорошее архитектурное решение, насколько оно подходит для масштабируемости.
 - Насколько я правильно использовал Gateway? То что я создал явялется им в привычном смысле для инженера, который что-то подобное разрабатывает? И насколько я правильно внутри использовал запрос к другому сервису, может быть стоит добавить для этого еще один слой абстракции?
Буду очень рад увидеть ответы на мои вопросы👍

2024-06-13 05:40 UTC, vaganov-vadim commented
Вне ревью - у тебя .idea не игнорируется с помощью .gitignore, т. к. папка .idea на уровень выше. Разберись с этим, пожалуйста :) Ещё имя приложение в settings.gradle разнится с названием папки, наверное стоит привести к одному значению.

2024-06-13 06:00 UTC, vaganov-vadim requested changes
Привет! Добавил своих мыслей. В целом подходы рабочие, но можно сделать ещё более гибко. Если будут вопросы - обращайся.

2024-06-13 06:00 UTC, vaganov-vadim commented on tg-bot-app/build.gradle
> +	id 'org.springframework.boot' version '2.7.5'
А почему понизили версию?)

2024-06-13 06:00 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/GpbApplication.java
> +		app.setDefaultProperties(Collections.singletonMap("server.port", "8086"));
А почему бы это просто в application.yaml не положить? :) Не замечание, просто интересно.

2024-06-13 06:00 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/config/RestTemplateConfig.java
> +    public RestTemplate restTemplate() {
Советую использовать RestClient (кажется, он появился в Spring Boot 3?) вместо RestTemplate, это рекомендация Spring.

2024-06-13 06:00 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/config/RestTemplateConfig.java
> +    private static final int CON_TIMEOUT = (int) TimeUnit.SECONDS.toMillis(3);
На будущее - лучше константы/переменные/конфигурационные элементы называть с мерой измерения. В данном случае, например - CONNECTION_TIMEOUT_MS. Это повышает читаемость, не приходится перепроверять самого себя, сразу есть контекст в голове, что у нас миллисекунды.

2024-06-13 06:00 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/config/RestTemplateConfig.java
> +    private static final int REQ_TIMEOUT = (int) TimeUnit.SECONDS.toMillis(30);
Я думаю, что тут можем обойтись без таких вычислений и просто написать число. Мы же и так знаем, сколько миллисекунд в секунде и вряд ли этот расчёт изменится когда-нибудь)

2024-06-13 06:00 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/config/RestTemplateConfig.java
> +public class RestTemplateConfig {
Кстати, многие свойства - таймаут, максимальное число коннектов и т. д., хорошо бы вынести в конфигурацию. Это то, чем мы можем захотеть управлять в моменте. Вдруг нам коннектов не хватит или значение для таймаута слишком маленькое? Придётся катить хотфикс и пересобирать приложение!

2024-06-13 06:00 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/config/ServerPortCustomizer.java
> +    public void customize(ConfigurableWebServerFactory factory) {
Не очень понял, зачем это нужно? Если есть какая-то особая причина, то лучше оставить здесь комментарий "зачем". Иначе выглядит как что-то лишнее, т. к. уже в другом месте определяли порт.

2024-06-13 06:00 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/factories/ResponseFactory.java
> +    private static final String URI = "http://localhost:8080/api/users";
Такое точно в конфиг, нельзя хардкодить url'ы - это штука изменяющаяся.

2024-06-13 06:00 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/factories/ResponseFactory.java
> +                case "/start" -> "Hello " + message.getChat().getFirstName();
В таком подходе есть одна проблема - расширяемость. Давай попробуем это зарефакторить под паттерн Command? Тогда мы сможем внедрять наши команды в этот класс и исполнять команду в зависимости от ввода пользователя.

2024-06-13 06:00 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/gateways/MiddleServiceUserGateway.java
> +        ResponseEntity<?> response = restTemplate.postForEntity(uri, user, String.class);
Если объявить ResponseEntity с дженерик-параметром String, тогда нам не придётся ниже кастить в String.

2024-06-13 06:00 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/gateways/MiddleServiceUserGateway.java
> +        return "Пользователь успешно зарегистрирован";
Немного логика расползается. Вроде успешный вариант мы обрабатываем при HttpStatus.OK, а получается все остальные предположительно ошибочные, но мы всё равно вернём "Пользовательно успешно зарегистрирован?"

2024-06-13 06:00 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/gateways/MiddleServiceUserGateway.java
> +public class MiddleServiceUserGateway {
Подход нормальный в целом. Единственное, т. к. это всё же внешнее взаимодействие - я бы его вынес в интерфейс, так проще реагировать на изменения и писать тесты.

2024-06-13 06:00 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/gateways/MiddleServiceUserGateway.java
> +    public String postRegisterUser(String uri, Message message) {
Не уверен на счёт сигнатуры. Возможно, должен быть специфический клиент, внутри которого уже известен url (из конфига, например) и на вход он принимает DTO (CreateUserRequest в твоём случае), а не Message - иначе у нас случается привязка клиента к телеграму, в чём большного смысла нет - можно просто их отвязать друг от друга.

2024-06-13 14:12 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/GpbApplication.java
> +		app.setDefaultProperties(Collections.singletonMap("server.port", "8086"));
Мне не нравилось, что моя idea плохо отображает работу приложения, а точнее пишет, что приложение не запустилось, а оно на самом деле запустилось, и не отображает соответственно разного рода информацию о работе

2024-06-13 14:25 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/gateways/MiddleServiceUserGateway.java
> +        return "Пользователь успешно зарегистрирован";
Здесь логика как раз реализована наоборот, статус код OK говорит нам об ошибке. Константин часто на своих лекциях упоминал, что подобным образом обрабатываются ошибки и в этом ответе приходит 
![image](https://github.com/gpb-it-factory/danyukovas-telegram-bot/assets/91426901/73e34740-d4a8-49e4-935a-4ffc93a2182b), а если ответ не ОК, значит все работает

2024-06-13 14:27 UTC, SiuSpacecowboy commented on tg-bot-app/build.gradle
> +	id 'org.springframework.boot' version '2.7.5'
Не работала конфигурация RestTemplate, сейчас попробую вернуть версию и сконфигурировать как раз RestClient

2024-06-14 13:50 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/config/ServerPortCustomizer.java
> +    public void customize(ConfigurableWebServerFactory factory) {
Да, без этой части все хорошо работает, убирал ее 👍

2024-06-14 16:29 UTC, SiuSpacecowboy commented on tg-bot-app/build.gradle
> +	id 'org.springframework.boot' version '2.7.5'
готово https://github.com/gpb-it-factory/danyukovas-telegram-bot/commit/066628a4e49dc5a2440cc495f7a194ee6950fe27

2024-06-14 16:29 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/config/RestTemplateConfig.java
> +    public RestTemplate restTemplate() {
готово: https://github.com/gpb-it-factory/danyukovas-telegram-bot/commit/066628a4e49dc5a2440cc495f7a194ee6950fe27

2024-06-14 16:30 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/config/RestTemplateConfig.java
> +    private static final int CON_TIMEOUT = (int) TimeUnit.SECONDS.toMillis(3);
Отличный совет, очень полезный 👍.

2024-06-14 16:30 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/config/RestTemplateConfig.java
> +    private static final int CON_TIMEOUT = (int) TimeUnit.SECONDS.toMillis(3);
готово: https://github.com/gpb-it-factory/danyukovas-telegram-bot/commit/066628a4e49dc5a2440cc495f7a194ee6950fe27

2024-06-14 16:31 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/config/RestTemplateConfig.java
> +    private static final int REQ_TIMEOUT = (int) TimeUnit.SECONDS.toMillis(30);
готово: https://github.com/gpb-it-factory/danyukovas-telegram-bot/commit/066628a4e49dc5a2440cc495f7a194ee6950fe27

2024-06-14 16:32 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/config/RestTemplateConfig.java
> +public class RestTemplateConfig {
Очень хороший совет, в будущем буду делать именно так 👍. Готово: https://github.com/gpb-it-factory/danyukovas-telegram-bot/commit/066628a4e49dc5a2440cc495f7a194ee6950fe27

2024-06-14 16:33 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/gateways/MiddleServiceUserGateway.java
> +        ResponseEntity<?> response = restTemplate.postForEntity(uri, user, String.class);
👍

2024-06-16 00:13 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/gateways/MiddleServiceUserGateway.java
> +public class MiddleServiceUserGateway {
Тут честно говоря тема полностью не раскрыта) Подобные "gateways" будут просто копировать контроллеры middleSerive'a. Так как в разных контроллерах будут разное количество запросов, наверное не получится сделать единый интерфейс(. Вот моя идея. Исходя из нее, мне все еще нужно будет как-то ее доработать, буду очень рад прочитать :+1:

2024-06-16 00:18 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/factories/ResponseFactory.java
> +                case "/start" -> "Hello " + message.getChat().getFirstName();
Переделал логику приложения под паттерн Command, очень буду ждать оценки реализации 👍 : https://github.com/gpb-it-factory/danyukovas-telegram-bot/commit/dd449354e040a1f79f1eda82e796f15a0047b1d7****

2024-06-16 00:19 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/gateways/MiddleServiceUserGateway.java
> +    public String postRegisterUser(String uri, Message message) {
Готово: https://github.com/gpb-it-factory/danyukovas-telegram-bot/commit/dd449354e040a1f79f1eda82e796f15a0047b1d7

2024-06-16 00:20 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/factories/ResponseFactory.java
> +    private static final String URI = "http://localhost:8080/api/users";
Готово: https://github.com/gpb-it-factory/danyukovas-telegram-bot/commit/dd449354e040a1f79f1eda82e796f15a0047b1d7

2024-06-17 15:26 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/gateways/MiddleServiceUserGateway.java
> +        return "Пользователь успешно зарегистрирован";
Тут я решил, что вся логика обработки ответов будет лежать в MIddleService, он при любом случае будет отдавать просто ответ в виде String, если я пойму, что так делать не получается, вернусь с задачей сделать под обработку ответов логику
Реализация: https://github.com/gpb-it-factory/danyukovas-telegram-bot/commit/2ec038200efb6155fcefce27f781acf89aa3d84b

2024-06-22 11:06 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/GpbApplication.java
> +		app.setDefaultProperties(Collections.singletonMap("server.port", "8086"));
Звучит странно, я думаю проблема в другом. Может, порт был занят просто?

2024-06-22 11:15 UTC, vaganov-vadim requested changes, later dismissed
Хорошая работа, стало ещё лучше! Добавил несколько комментов. Ещё один прыжок - и мы сделаем прям совсем красиво :)

2024-06-22 11:15 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/config/AppConfig.java
> +@PropertySource("classpath:http-client-config.yml")
В целом, как мне кажется, проще это сложить в application.yml, тогда нет особо смысла в дополнительных конструкциях. Не так уж много у тебя настроек в данный момент.

2024-06-22 11:15 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/factories/CommandFactory.java
> +    public CommandFactory(StartCommand startCommand, PingCommand pingCommand,
От одной проблемы мы так и не избавились. Новая команда должна всегда попадать в этот класс, то есть это будет постоянное место для изменений и конфликтов.

2024-06-22 11:15 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/factories/CommandFactory.java
> +    public CommandFactory(StartCommand startCommand, PingCommand pingCommand,
Есть лайфхак, чтобы всем этим не заниматься - название команды хранить в самой команде, а команды внедрять в компоненты как Set<Command>, тогда ты будешь зависеть от конкретных реализаций.

2024-06-22 11:15 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/handlers/CommandInvoker.java
> +public class CommandInvoker {
Мне кажется, что слегка избыточная абстракция, можно просто вызывать сами команды.

2024-06-22 11:15 UTC, vaganov-vadim commented
+ конфликт надо разрешить

2024-06-23 19:16 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/config/AppConfig.java
> +@PropertySource("classpath:http-client-config.yml")
готово 👍

2024-06-23 19:56 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/factories/CommandFactory.java
> +    public CommandFactory(StartCommand startCommand, PingCommand pingCommand,
Вау, я не знал, что спринг такой умный и такие вещи умеет делать, так бы сразу так сделать, спасибо большое за совет :+1:

2024-06-23 20:23 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/handlers/CommandInvoker.java
> +public class CommandInvoker {
👍

2024-06-23 21:03 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/GpbApplication.java
> +		app.setDefaultProperties(Collections.singletonMap("server.port", "8086"));
хм, попробовал еще раз сконфигурировать через application, все нормально сработало 🤔

2024-06-23 21:08 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/factories/CommandFactory.java
> +    public CommandFactory(StartCommand startCommand, PingCommand pingCommand,
Все изменил, в любом случае, пришло пару команд напрямую инжектить, чтобы код был красивый
Реализация: https://github.com/gpb-it-factory/danyukovas-telegram-bot/pull/9/commits/7a5ee929c952b2217ff899ca29dda40e8e458051

2024-06-25 16:05 UTC, vaganov-vadim approved these changes
Привет! Всё круто. Я оставил ещё пару комментов по возможным улучшениям, но они неблокирующие. Аппрув.

2024-06-25 16:05 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/factories/CommandFactory.java
> +        if (text != null) {
Тут можно инвертировать, чтобы большая часть метода была не внутри if.

if (text == null) return nonTextCommand.

2024-06-25 16:05 UTC, vaganov-vadim commented on tg-bot-app/src/main/java/com/example/gpb/factories/CommandFactory.java
> +        if (text != null) {
Мне кажется, что wrongCommand и nonTextCommand можно слить в одну. Суть вроде одна. Да и может ли прилететь пустая команда?

2024-06-25 18:05 UTC, SiuSpacecowboy commented on tg-bot-app/src/main/java/com/example/gpb/factories/CommandFactory.java
> +        if (text != null) {
тут может прилететь в команду картинка, я это и обрабатываю :+1:

2024-06-25 18:39 UTC, merged